self-xdsd/self-pm

.rultor.yml, .travis.yml, checkstyle.xml, pom.xml, src/main/java/com/selfxdsd/selfpm/SelfPmApplication.java, src/test/java/com/selfxdsd/selfpm/SelfPmApplicationTests.java
fixes #4 
Maven profiles for: checkstyle, testCoverage, signArtifacts and deployToGithub
=> Maven profiles

pom.xml
=> Added self-core and test dependencies

pom.xml, src/main/java/com/selfxdsd/selfpm/AcceptInvitations.java, src/main/java/com/selfxdsd/selfpm/ScheduledTasks.java, src/main/java/com/selfxdsd/selfpm/SelfCoreComponent.java, src/test/java/com/selfxdsd/selfpm/SelfPmApplicationITCase.java, src/test/resources/createDb.sql, src/test/resources/insertTestData.sql
PR for #3 
fixes #8 as well. 
Added ``AcceptInvitations`` which checks for and accepts PM invitations every 10 minutes
Added ``SelfCoreComponent`` which represents Self's core.
=> AcceptInvitations, SelfCoreComponent and itcases profile

src/test/java/com/selfxdsd/selfpm/AcceptInvitationsTestCase.java
=> #3 AcceptInvitations unit tests

.rultor.yml, pom.xml, release.sh
=> #11 release scripts

src/main/resources/commands_en.properties, src/main/resources/responses_en.properties
=> #15 english files

pom.xml, src/main/java/com/selfxdsd/selfpm/Ping.java, src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/main/resources/application.properties
Fixes #14 
Left puzzle to continue work in another task.
=> Webhooks scaffolding

pom.xml, src/main/java/com/selfxdsd/selfpm/SelfCoreComponent.java, src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
PR for #18 
Updated to self-core 0.0.8
Finished implementing Webhook.github(...)
Added unit tests
=> #18 Finished Webhooks.github

src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
Fixes #21 
Left puzzle to continue work.
=> #21 scaffolding of Github Webhook signature calculation

src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
=> #26 Constructed the Github Event

pom.xml, src/main/java/com/selfxdsd/selfpm/Webhooks.java
Fixes #29 
core version is 0.0.20
storage version is 0.0.7
=> #29 updated core and storage.

src/main/resources/commands_en.properties, src/main/resources/responses_en.properties
=> #28 commands and responses updated

src/main/java/com/selfxdsd/selfpm/ReviewUnassignedTasks.java, src/test/java/com/selfxdsd/selfpm/ReviewUnassignedTasksTestCase.java
=> #31 ReviewUnassignedTasks every 10min + unit tests

src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
=> #35 resolve newIssue and reopened ev types + unit tests

pom.xml
FIxes #39 
This update makes the PM handle comments events.
=> #39 updated core to 25 and storage to 11

src/main/java/com/selfxdsd/selfpm/ReviewAssignedTasks.java, src/main/resources/responses_en.properties
Fixes #40 
The PMs are reviewing their assigned tasks every 6 hours.
=> #40 review assigned tasks every 6 hours

src/main/resources/application.properties
=> #43 Configured log file.

README.md, pom.xml, release.sh
=> #46 Update to core 27 and storage 12

src/main/java/com/selfxdsd/selfpm/Webhooks.java
=> #49 resolve pull_request events too

pom.xml, src/main/java/com/selfxdsd/selfpm/GithubWebhookEvent.java, src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/GithubWebhookEventTestCase.java
Fixes #58 
Updated self-core to 0.0.33.
Forward the PUSH github webhook event to SelfTodos.
Extracted and tested class GithubWebhookEvent.
=> #58 forward PUSH to SelfTodos

src/main/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemoval.java, src/test/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemovalTestCase.java
Closes #61 
- left puzzle to proper remove a Contract when API is available.
=> #61 Review contracts marked for removal.

src/main/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemoval.java, src/main/java/com/selfxdsd/selfpm/SelfPmApplication.java, src/test/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemovalTestCase.java
- changed version to the current one.
@amihaiemil I forgot to remove the puzzle #61.
=> Removed puzzle for #61.

src/main/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemoval.java, src/test/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemovalTestCase.java
=> #63 Used Contract#remove to remove a contract.

pom.xml, src/main/java/com/selfxdsd/selfpm/ReviewAssignedTasks.java, src/main/java/com/selfxdsd/selfpm/ReviewUnassignedTasks.java, src/main/java/com/selfxdsd/selfpm/SelfCoreComponent.java
Fixes #72 
Also made 2 changes for QA purposes, which will be reverted:
-review unassigned tasks every 3 minutes
-review assigned tasks every 4 minutes
=> #72 updated to core 42 and storage 19

src/main/resources/commands_en.properties, src/main/resources/responses_en.properties
=> messages updated according to core

src/main/java/com/selfxdsd/selfpm/ReviewAssignedTasks.java, src/main/java/com/selfxdsd/selfpm/ReviewUnassignedTasks.java, src/test/java/com/selfxdsd/selfpm/ReviewAssignedTasksTestCase.java
=> #76 catch exceptions on review and unit tests

pom.xml
=> #78 core 43 and storage 20

src/main/java/com/selfxdsd/selfpm/ReviewAssignedTasks.java, src/main/java/com/selfxdsd/selfpm/ReviewUnassignedTasks.java
Fixes #80 
Went back to the old timers: review unassigned tasks every 10min and assigned tasks every 6 hours.
=> #80 unassingned tasks every 10min, assigned tasks every 6 hours

src/main/java/com/selfxdsd/selfpm/Ping.java, src/main/resources/application.properties
=> #81 print build version on /ping

LICENSE, src/main/java/com/selfxdsd/selfpm/AcceptInvitations.java, src/main/java/com/selfxdsd/selfpm/GithubWebhookEvent.java, src/main/java/com/selfxdsd/selfpm/Ping.java, src/main/java/com/selfxdsd/selfpm/ReviewAssignedTasks.java, src/main/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemoval.java, src/main/java/com/selfxdsd/selfpm/ReviewUnassignedTasks.java, src/main/java/com/selfxdsd/selfpm/SelfCoreComponent.java, src/main/java/com/selfxdsd/selfpm/SelfPmApplication.java, src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/AcceptInvitationsTestCase.java, src/test/java/com/selfxdsd/selfpm/GithubWebhookEventTestCase.java, src/test/java/com/selfxdsd/selfpm/ReviewAssignedTasksTestCase.java, src/test/java/com/selfxdsd/selfpm/ReviewContractsMarkedForRemovalTestCase.java, src/test/java/com/selfxdsd/selfpm/ReviewUnassignedTasksTestCase.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
=> 2021, happy new year

pom.xml, src/main/java/com/selfxdsd/selfpm/GitlabWebhookEvent.java, src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
Fixes #86 
Updated to core 55 and storage 25;
Implemented and tested Webhooks.gitlab(...);
Left puzzle to implement GitlabWebhookEvent;
=> #86 GitLab Webhook Implemented

src/main/java/com/selfxdsd/selfpm/GitlabWebhookEvent.java, src/test/java/com/selfxdsd/selfpm/GitlabWebhookEventTestCase.java
PR for #88 
Implemented and tested the GitlabWebhookEvent class.
=> #88 GitlabWebhookEvent implemented and tested

src/main/java/com/selfxdsd/selfpm/GitlabWebhookEvent.java, src/test/java/com/selfxdsd/selfpm/GitlabWebhookEventTestCase.java
Fixes #90 
Check the action attribute instead of the state.
=> #90 check action instead of state

pom.xml, src/main/java/com/selfxdsd/selfpm/PayInvoices.java, src/test/java/com/selfxdsd/selfpm/PayInvoicesTestCase.java
=> #71 Pay Active Invoices Every Monday.

src/main/java/com/selfxdsd/selfpm/PayInvoices.java, src/test/java/com/selfxdsd/selfpm/PayInvoicesTestCase.java
=> #99 Fixed and test cron expression.

pom.xml
=> updated to core 72 and storage 68

pom.xml, src/main/java/com/selfxdsd/selfpm/ReviewAssignedTasks.java, src/main/java/com/selfxdsd/selfpm/ReviewUnassignedTasks.java, src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
=> #118 Repo full_name From Payload

src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
=> #125 Take Alternate Repo New Name from Change Object

src/main/java/com/selfxdsd/selfpm/Webhooks.java, src/test/java/com/selfxdsd/selfpm/WebhooksTestCase.java
=> #127 unit test and fix

src/main/java/com/selfxdsd/selfpm/SelfCoreComponent.java
=> #130 SelfCoreComponent request scoped

src/main/resources/responses_en.properties
=> revised messages
